#!/bin/bash
top=$(realpath $PREFIX/..)
echo $top

prog=afvslt
export TDIR=$PREFIX/lib/python3.11/site-packages/torch
set -x
g++ -O2 -std=c++17 -ggdb3 \
    -o $top/$prog $top/spng/test/${prog}.cpp \
    -isystem $PREFIX/include \
    -isystem PREFIX/targets/x86_64-linux/include \
    -isystem $TDIR/include \
    -isystem $TDIR/include/torch/csrc/api/include \
    -L $PREFIX/lib \
    -L $PREFIX/targets/x86_64-linux/lib \
    -L $TDIR/lib \
    -laf \
    -ltorch -ltorch_cpu -lc10 -lc10_cuda -ltorch_cuda \
    -Wl,--no-as-needed,"$TDIR/lib/libtorch.so" \
    -Wl,--no-as-needed,"$TDIR/lib/libtorch_cpu.so" \
    -Wl,--no-as-needed,"$TDIR/lib/libtorch_cuda.so" \
    -lcudart -lcuda \
    -Wl,-rpath,$PREFIX/lib:$PREFIX/targets/x86_64-linux/lib:$TDIR/lib || exit 1

